builds:
  - id: compose-to-intellij
    main: ./cmd/compose-to-intellij/main.go
    goos:
      - darwin
      - linux

archives:
  - replacements:
      darwin: macOS
      linux: Linux
      386: i386
      amd64: x86_64

brews:
  - name: compose-to-intellij
    homepage: https://github.com/J-R-Oliver/homebrew-tools
    description: Command-line application to convert Docker Compose env vars to IntelliJ format
    folder: Formula
    license: Unlicense
    tap:
      owner: J-R-Oliver
      name: homebrew-tools

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^build:'
      - '^ci:'
      - '^docs:'
      - '^refactor:'
      - '^style:'
